"use client";

import React, { useState, useEffect, use, useRef } from "react";
import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
);

const LANGS = ["en","nl","de","fr","es","it","pt","pl","ru","ja","zh","ko","ar","tr","sv","da","no","hi","id","th"];

// UI labels per taal — kleine statische set, geen API nodig
const UI: Record<string, Record<string, string>> = {
  en: { ingredients: "Ingredients", instructions: "Instructions", prepTime: "Prep time", servings: "Servings", calories: "Calories", difficulty: "Difficulty", min: "min", people: "people", kcal: "kcal", aiChecked: "AI Generated & Quality Checked", aiText: "This recipe was generated by AI and verified before going live — completeness, ratios, logic and prep time all checked.", allRecipes: "All recipes", share: "Share", copyLink: "Copy link", copied: "Copied!", madeThis: "Did you make this?", madeThisSub: "Upload your photo and show how it turned out.", yourName: "Your name (optional)", yourTip: "Short tip or variation (optional)", uploadPhoto: "Upload photo", changePhoto: "Change photo", post: "Post →", communityTitle: "How others made it", cookIt: "Cook it. Post it.", cookItSub: "Your version of this AI recipe. A tip, variation, or just a great photo.", whatDoYouThink: "What do you think?" },
  nl: { ingredients: "Ingrediënten", instructions: "Bereidingswijze", prepTime: "Bereidingstijd", servings: "Porties", calories: "Calorieën", difficulty: "Moeilijkheid", min: "min", people: "personen", kcal: "kcal", aiChecked: "AI Gegenereerd & Kwaliteitsgecheckt", aiText: "Dit recept is gegenereerd door AI en geverifieerd voor publicatie — volledigheid, verhoudingen, logica en bereidingstijd allemaal gecheckt.", allRecipes: "Alle recepten", share: "Delen", copyLink: "Link kopiëren", copied: "Gekopieerd!", madeThis: "Heb jij dit gemaakt?", madeThisSub: "Upload je foto en laat zien hoe het bij jou uitpakte.", yourName: "Jouw naam (optioneel)", yourTip: "Korte tip of variatie (optioneel)", uploadPhoto: "Foto uploaden", changePhoto: "Andere foto", post: "Plaatsen →", communityTitle: "Zo maakten anderen het", cookIt: "Kook het. Post het.", cookItSub: "Jouw versie van dit AI-recept. Een tip, variatie of gewoon een mooie foto.", whatDoYouThink: "Wat vind je?" },
  de: { ingredients: "Zutaten", instructions: "Zubereitung", prepTime: "Zubereitungszeit", servings: "Portionen", calories: "Kalorien", difficulty: "Schwierigkeit", min: "Min", people: "Personen", kcal: "kcal", aiChecked: "KI-generiert & Qualitätsgeprüft", aiText: "Dieses Rezept wurde von KI erstellt und vor der Veröffentlichung überprüft — Vollständigkeit, Mengen, Logik und Zubereitungszeit alle geprüft.", allRecipes: "Alle Rezepte", share: "Teilen", copyLink: "Link kopieren", copied: "Kopiert!", madeThis: "Hast du das gemacht?", madeThisSub: "Lade dein Foto hoch und zeig, wie es bei dir geworden ist.", yourName: "Dein Name (optional)", yourTip: "Kurzer Tipp oder Variation (optional)", uploadPhoto: "Foto hochladen", changePhoto: "Anderes Foto", post: "Posten →", communityTitle: "So haben andere es gemacht", cookIt: "Koche es. Poste es.", cookItSub: "Deine Version dieses KI-Rezepts. Ein Tipp, eine Variation oder einfach ein tolles Foto.", whatDoYouThink: "Was denkst du?" },
  fr: { ingredients: "Ingrédients", instructions: "Préparation", prepTime: "Temps de préparation", servings: "Portions", calories: "Calories", difficulty: "Difficulté", min: "min", people: "personnes", kcal: "kcal", aiChecked: "Généré par IA & Contrôle qualité", aiText: "Cette recette a été générée par IA et vérifiée avant publication — complétude, proportions, logique et temps de préparation tous vérifiés.", allRecipes: "Toutes les recettes", share: "Partager", copyLink: "Copier le lien", copied: "Copié!", madeThis: "Vous l'avez préparé ?", madeThisSub: "Uploadez votre photo et montrez comment ça s'est passé.", yourName: "Votre nom (optionnel)", yourTip: "Conseil ou variation (optionnel)", uploadPhoto: "Télécharger une photo", changePhoto: "Changer la photo", post: "Publier →", communityTitle: "Comment les autres l'ont préparé", cookIt: "Cuisinez-le. Publiez-le.", cookItSub: "Votre version de cette recette IA. Un conseil, une variation ou juste une belle photo.", whatDoYouThink: "Qu'en pensez-vous ?" },
  es: { ingredients: "Ingredientes", instructions: "Preparación", prepTime: "Tiempo de preparación", servings: "Porciones", calories: "Calorías", difficulty: "Dificultad", min: "min", people: "personas", kcal: "kcal", aiChecked: "Generado por IA & Control de calidad", aiText: "Esta receta fue generada por IA y verificada antes de publicarse — completitud, proporciones, lógica y tiempo de preparación todos revisados.", allRecipes: "Todas las recetas", share: "Compartir", copyLink: "Copiar enlace", copied: "¡Copiado!", madeThis: "¿Lo preparaste?", madeThisSub: "Sube tu foto y muestra cómo te quedó.", yourName: "Tu nombre (opcional)", yourTip: "Consejo o variación (opcional)", uploadPhoto: "Subir foto", changePhoto: "Cambiar foto", post: "Publicar →", communityTitle: "Cómo lo prepararon otros", cookIt: "Cocínalo. Publícalo.", cookItSub: "Tu versión de esta receta IA. Un consejo, una variación o simplemente una gran foto.", whatDoYouThink: "¿Qué piensas?" },
  it: { ingredients: "Ingredienti", instructions: "Preparazione", prepTime: "Tempo di preparazione", servings: "Porzioni", calories: "Calorie", difficulty: "Difficoltà", min: "min", people: "persone", kcal: "kcal", aiChecked: "Generato da IA & Controllo qualità", aiText: "Questa ricetta è stata generata dall'IA e verificata prima della pubblicazione — completezza, proporzioni, logica e tempi di preparazione tutti controllati.", allRecipes: "Tutte le ricette", share: "Condividi", copyLink: "Copia link", copied: "Copiato!", madeThis: "L'hai preparato?", madeThisSub: "Carica la tua foto e mostra come è venuto.", yourName: "Il tuo nome (opzionale)", yourTip: "Consiglio o variazione (opzionale)", uploadPhoto: "Carica foto", changePhoto: "Cambia foto", post: "Pubblica →", communityTitle: "Come lo hanno preparato gli altri", cookIt: "Cucinalo. Pubblicalo.", cookItSub: "La tua versione di questa ricetta IA. Un consiglio, una variazione o solo una bella foto.", whatDoYouThink: "Cosa ne pensi?" },
  pt: { ingredients: "Ingredientes", instructions: "Preparo", prepTime: "Tempo de preparo", servings: "Porções", calories: "Calorias", difficulty: "Dificuldade", min: "min", people: "pessoas", kcal: "kcal", aiChecked: "Gerado por IA & Controle de qualidade", aiText: "Esta receita foi gerada por IA e verificada antes de ser publicada — completude, proporções, lógica e tempo de preparo todos verificados.", allRecipes: "Todas as receitas", share: "Compartilhar", copyLink: "Copiar link", copied: "Copiado!", madeThis: "Você preparou isso?", madeThisSub: "Envie sua foto e mostre como ficou.", yourName: "Seu nome (opcional)", yourTip: "Dica ou variação (opcional)", uploadPhoto: "Enviar foto", changePhoto: "Mudar foto", post: "Publicar →", communityTitle: "Como outros prepararam", cookIt: "Cozinhe. Publique.", cookItSub: "Sua versão desta receita de IA. Uma dica, variação ou apenas uma ótima foto.", whatDoYouThink: "O que você acha?" },
  pl: { ingredients: "Składniki", instructions: "Przygotowanie", prepTime: "Czas przygotowania", servings: "Porcje", calories: "Kalorie", difficulty: "Trudność", min: "min", people: "osoby", kcal: "kcal", aiChecked: "Wygenerowane przez AI & Kontrola jakości", aiText: "Ten przepis został wygenerowany przez AI i zweryfikowany przed publikacją — kompletność, proporcje, logika i czas przygotowania sprawdzone.", allRecipes: "Wszystkie przepisy", share: "Udostępnij", copyLink: "Kopiuj link", copied: "Skopiowano!", madeThis: "Zrobiłeś to?", madeThisSub: "Prześlij swoje zdjęcie i pokaż, jak wyszło.", yourName: "Twoje imię (opcjonalnie)", yourTip: "Krótka wskazówka lub wariacja (opcjonalnie)", uploadPhoto: "Prześlij zdjęcie", changePhoto: "Zmień zdjęcie", post: "Opublikuj →", communityTitle: "Jak inni to zrobili", cookIt: "Ugotuj. Opublikuj.", cookItSub: "Twoja wersja tego przepisu AI. Wskazówka, wariacja lub po prostu świetne zdjęcie.", whatDoYouThink: "Co myślisz?" },
  ru: { ingredients: "Ингредиенты", instructions: "Приготовление", prepTime: "Время приготовления", servings: "Порции", calories: "Калории", difficulty: "Сложность", min: "мин", people: "человек", kcal: "ккал", aiChecked: "Создано ИИ & Проверка качества", aiText: "Этот рецепт создан ИИ и проверен перед публикацией — полнота, пропорции, логика и время приготовления проверены.", allRecipes: "Все рецепты", share: "Поделиться", copyLink: "Копировать ссылку", copied: "Скопировано!", madeThis: "Вы приготовили это?", madeThisSub: "Загрузите фото и покажите, как получилось.", yourName: "Ваше имя (необязательно)", yourTip: "Совет или вариация (необязательно)", uploadPhoto: "Загрузить фото", changePhoto: "Изменить фото", post: "Опубликовать →", communityTitle: "Как это сделали другие", cookIt: "Приготовьте. Опубликуйте.", cookItSub: "Ваша версия этого рецепта ИИ. Совет, вариация или просто отличное фото.", whatDoYouThink: "Что вы думаете?" },
  ja: { ingredients: "材料", instructions: "作り方", prepTime: "調理時間", servings: "人分", calories: "カロリー", difficulty: "難易度", min: "分", people: "人分", kcal: "kcal", aiChecked: "AI生成・品質チェック済み", aiText: "このレシピはAIによって生成され、公開前に検証されました — 完全性、分量、ロジック、調理時間すべてを確認済みです。", allRecipes: "すべてのレシピ", share: "シェア", copyLink: "リンクをコピー", copied: "コピーしました！", madeThis: "作りましたか？", madeThisSub: "写真をアップロードして、どうなったか見せてください。", yourName: "お名前（任意）", yourTip: "ヒントやアレンジ（任意）", uploadPhoto: "写真をアップロード", changePhoto: "写真を変更", post: "投稿する →", communityTitle: "みんなの作り方", cookIt: "作って。投稿して。", cookItSub: "このAIレシピのあなたのバージョン。ヒント、アレンジ、または素晴らしい写真。", whatDoYouThink: "どう思いますか？" },
  zh: { ingredients: "食材", instructions: "做法", prepTime: "准备时间", servings: "份量", calories: "卡路里", difficulty: "难度", min: "分钟", people: "人份", kcal: "千卡", aiChecked: "AI生成 & 质量检验", aiText: "此食谱由AI生成，发布前经过验证 — 完整性、比例、逻辑和准备时间均已检查。", allRecipes: "所有食谱", share: "分享", copyLink: "复制链接", copied: "已复制！", madeThis: "你做了这道菜吗？", madeThisSub: "上传你的照片，展示你的成品。", yourName: "你的名字（可选）", yourTip: "简短提示或变化（可选）", uploadPhoto: "上传照片", changePhoto: "更换照片", post: "发布 →", communityTitle: "其他人是怎么做的", cookIt: "做它。发布它。", cookItSub: "你的AI食谱版本。一个提示、变化或只是一张好照片。", whatDoYouThink: "你怎么看？" },
  ko: { ingredients: "재료", instructions: "조리법", prepTime: "준비 시간", servings: "인분", calories: "칼로리", difficulty: "난이도", min: "분", people: "인분", kcal: "kcal", aiChecked: "AI 생성 & 품질 검증", aiText: "이 레시피는 AI가 생성하고 게시 전에 검증되었습니다 — 완전성, 비율, 논리 및 준비 시간 모두 확인했습니다.", allRecipes: "모든 레시피", share: "공유", copyLink: "링크 복사", copied: "복사됨!", madeThis: "이것을 만들었나요?", madeThisSub: "사진을 업로드하고 어떻게 나왔는지 보여주세요.", yourName: "이름 (선택사항)", yourTip: "간단한 팁 또는 변형 (선택사항)", uploadPhoto: "사진 업로드", changePhoto: "사진 변경", post: "게시 →", communityTitle: "다른 사람들이 만든 방법", cookIt: "요리하세요. 게시하세요.", cookItSub: "이 AI 레시피의 당신만의 버전. 팁, 변형 또는 멋진 사진.", whatDoYouThink: "어떻게 생각하세요?" },
  ar: { ingredients: "المكونات", instructions: "طريقة التحضير", prepTime: "وقت التحضير", servings: "الحصص", calories: "السعرات", difficulty: "الصعوبة", min: "دقيقة", people: "أشخاص", kcal: "سعرة", aiChecked: "وصفة مولدة بالذكاء الاصطناعي & مفحوصة", aiText: "تم إنشاء هذه الوصفة بواسطة الذكاء الاصطناعي والتحقق منها قبل النشر.", allRecipes: "جميع الوصفات", share: "مشاركة", copyLink: "نسخ الرابط", copied: "تم النسخ!", madeThis: "هل جربت هذه الوصفة؟", madeThisSub: "ارفع صورتك وأرنا كيف جاءت النتيجة.", yourName: "اسمك (اختياري)", yourTip: "نصيحة أو تعديل (اختياري)", uploadPhoto: "رفع صورة", changePhoto: "تغيير الصورة", post: "نشر →", communityTitle: "كيف صنعها الآخرون", cookIt: "اطبخه. انشره.", cookItSub: "نسختك من وصفة الذكاء الاصطناعي هذه.", whatDoYouThink: "ما رأيك؟" },
  tr: { ingredients: "Malzemeler", instructions: "Hazırlanışı", prepTime: "Hazırlık süresi", servings: "Porsiyon", calories: "Kalori", difficulty: "Zorluk", min: "dk", people: "kişilik", kcal: "kcal", aiChecked: "Yapay Zeka ile Üretildi & Kalite Kontrol", aiText: "Bu tarif yapay zeka tarafından oluşturuldu ve yayınlanmadan önce doğrulandı.", allRecipes: "Tüm tarifler", share: "Paylaş", copyLink: "Bağlantıyı kopyala", copied: "Kopyalandı!", madeThis: "Bunu yaptınız mı?", madeThisSub: "Fotoğrafınızı yükleyin ve nasıl çıktığını gösterin.", yourName: "Adınız (isteğe bağlı)", yourTip: "Kısa ipucu veya değişiklik (isteğe bağlı)", uploadPhoto: "Fotoğraf yükle", changePhoto: "Fotoğrafı değiştir", post: "Paylaş →", communityTitle: "Diğerleri nasıl yaptı", cookIt: "Pişirin. Paylaşın.", cookItSub: "Bu AI tarifinin sizin versiyonunuz.", whatDoYouThink: "Ne düşünüyorsunuz?" },
  sv: { ingredients: "Ingredienser", instructions: "Tillagning", prepTime: "Tillagningstid", servings: "Portioner", calories: "Kalorier", difficulty: "Svårighetsgrad", min: "min", people: "personer", kcal: "kcal", aiChecked: "AI-genererat & Kvalitetskontrollerat", aiText: "Detta recept genererades av AI och verifierades innan publicering.", allRecipes: "Alla recept", share: "Dela", copyLink: "Kopiera länk", copied: "Kopierat!", madeThis: "Har du lagat detta?", madeThisSub: "Ladda upp ditt foto och visa hur det gick.", yourName: "Ditt namn (valfritt)", yourTip: "Kort tips eller variation (valfritt)", uploadPhoto: "Ladda upp foto", changePhoto: "Byt foto", post: "Publicera →", communityTitle: "Hur andra lagade det", cookIt: "Laga det. Dela det.", cookItSub: "Din version av detta AI-recept.", whatDoYouThink: "Vad tycker du?" },
  da: { ingredients: "Ingredienser", instructions: "Fremgangsmåde", prepTime: "Tilberedningstid", servings: "Portioner", calories: "Kalorier", difficulty: "Sværhedsgrad", min: "min", people: "personer", kcal: "kcal", aiChecked: "AI-genereret & Kvalitetskontrolleret", aiText: "Denne opskrift blev genereret af AI og verificeret inden publicering.", allRecipes: "Alle opskrifter", share: "Del", copyLink: "Kopier link", copied: "Kopieret!", madeThis: "Lavede du dette?", madeThisSub: "Upload dit foto og vis, hvordan det gik.", yourName: "Dit navn (valgfrit)", yourTip: "Kort tip eller variation (valgfrit)", uploadPhoto: "Upload foto", changePhoto: "Skift foto", post: "Publicer →", communityTitle: "Sådan lavede andre det", cookIt: "Lav det. Del det.", cookItSub: "Din version af denne AI-opskrift.", whatDoYouThink: "Hvad synes du?" },
  no: { ingredients: "Ingredienser", instructions: "Fremgangsmåte", prepTime: "Tilberedningstid", servings: "Porsjoner", calories: "Kalorier", difficulty: "Vanskelighetsgrad", min: "min", people: "personer", kcal: "kcal", aiChecked: "AI-generert & Kvalitetskontrollert", aiText: "Denne oppskriften ble generert av AI og verifisert før publisering.", allRecipes: "Alle oppskrifter", share: "Del", copyLink: "Kopier lenke", copied: "Kopiert!", madeThis: "Lagde du dette?", madeThisSub: "Last opp bildet ditt og vis hvordan det gikk.", yourName: "Ditt navn (valgfritt)", yourTip: "Kort tips eller variasjon (valgfritt)", uploadPhoto: "Last opp bilde", changePhoto: "Bytt bilde", post: "Publiser →", communityTitle: "Slik lagde andre det", cookIt: "Lag det. Del det.", cookItSub: "Din versjon av denne AI-oppskriften.", whatDoYouThink: "Hva synes du?" },
  hi: { ingredients: "सामग्री", instructions: "बनाने की विधि", prepTime: "तैयारी का समय", servings: "सर्विंग", calories: "कैलोरी", difficulty: "कठिनाई", min: "मिनट", people: "लोगों के लिए", kcal: "kcal", aiChecked: "AI द्वारा निर्मित & गुणवत्ता जांच", aiText: "यह रेसिपी AI द्वारा बनाई गई और प्रकाशन से पहले सत्यापित की गई।", allRecipes: "सभी रेसिपी", share: "साझा करें", copyLink: "लिंक कॉपी करें", copied: "कॉपी हो गया!", madeThis: "क्या आपने यह बनाया?", madeThisSub: "अपनी फोटो अपलोड करें और दिखाएं कैसा बना।", yourName: "आपका नाम (वैकल्पिक)", yourTip: "छोटी सी टिप या बदलाव (वैकल्पिक)", uploadPhoto: "फोटो अपलोड करें", changePhoto: "फोटो बदलें", post: "पोस्ट करें →", communityTitle: "दूसरों ने कैसे बनाया", cookIt: "बनाएं। शेयर करें।", cookItSub: "इस AI रेसिपी का आपका संस्करण।", whatDoYouThink: "आप क्या सोचते हैं?" },
  id: { ingredients: "Bahan-bahan", instructions: "Cara Membuat", prepTime: "Waktu persiapan", servings: "Porsi", calories: "Kalori", difficulty: "Kesulitan", min: "menit", people: "orang", kcal: "kkal", aiChecked: "Dibuat oleh AI & Kontrol Kualitas", aiText: "Resep ini dibuat oleh AI dan diverifikasi sebelum dipublikasikan.", allRecipes: "Semua resep", share: "Bagikan", copyLink: "Salin tautan", copied: "Disalin!", madeThis: "Apakah Anda membuatnya?", madeThisSub: "Unggah foto Anda dan tunjukkan hasilnya.", yourName: "Nama Anda (opsional)", yourTip: "Tips singkat atau variasi (opsional)", uploadPhoto: "Unggah foto", changePhoto: "Ganti foto", post: "Posting →", communityTitle: "Bagaimana orang lain membuatnya", cookIt: "Masak. Posting.", cookItSub: "Versi Anda dari resep AI ini.", whatDoYouThink: "Apa pendapat Anda?" },
  th: { ingredients: "ส่วนผสม", instructions: "วิธีทำ", prepTime: "เวลาเตรียม", servings: "ที่เสิร์ฟ", calories: "แคลอรี่", difficulty: "ความยาก", min: "นาที", people: "คน", kcal: "กิโลแคลอรี่", aiChecked: "สร้างโดย AI & ตรวจสอบคุณภาพ", aiText: "สูตรนี้สร้างโดย AI และตรวจสอบก่อนเผยแพร่", allRecipes: "สูตรอาหารทั้งหมด", share: "แชร์", copyLink: "คัดลอกลิงก์", copied: "คัดลอกแล้ว!", madeThis: "คุณทำสิ่งนี้หรือเปล่า?", madeThisSub: "อัปโหลดรูปภาพของคุณและแสดงผลลัพธ์", yourName: "ชื่อของคุณ (ไม่บังคับ)", yourTip: "เคล็ดลับสั้นหรือการดัดแปลง (ไม่บังคับ)", uploadPhoto: "อัปโหลดรูปภาพ", changePhoto: "เปลี่ยนรูปภาพ", post: "โพสต์ →", communityTitle: "คนอื่นทำอย่างไร", cookIt: "ทำมัน. โพสต์มัน.", cookItSub: "เวอร์ชันของคุณของสูตร AI นี้", whatDoYouThink: "คุณคิดอย่างไร?" },
};

function getUI(lang: string) {
  return UI[lang] || UI.en;
}

export default function TranslatedRecipePage({ params }: { params: Promise<{ lang: string; slug: string }> }) {
  const { lang, slug } = use(params);
  const [recipe, setRecipe] = useState<any>(null);
  const [translation, setTranslation] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const ui = getUI(lang);

  useEffect(() => {
    async function fetchData() {
      // Haal vertaling op via slug + lang
      // Gebruik raw fetch om dubbele URL-encoding door Supabase JS client te voorkomen
      const url = `${process.env.NEXT_PUBLIC_SUPABASE_URL}/rest/v1/recipe_translations?select=*&lang=eq.${encodeURIComponent(lang)}&slug=eq.${(()=>{try{let s=decodeURIComponent(slug);return decodeURIComponent(s)}catch{return decodeURIComponent(slug)}})()}&limit=1`;
      const res = await fetch(url, {
        headers: {
          apikey: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
          Authorization: `Bearer ${process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!}`,
        },
      });
      const rows = await res.json();
      const trans = rows?.[0] ?? null;

      if (!trans) { setLoading(false); return; }
      setTranslation(trans);

      // Haal basisdata op (afbeelding, score, reactions etc.)
      const { data: rec } = await supabase
        .from("recipes")
        .select("id, image_url, ai_score, prep_time, servings, calories, difficulty, reactions_want, reactions_made, reactions_favorite")
        .eq("id", trans.recipe_id)
        .single();

      setRecipe(rec);
      setLoading(false);
    }
    fetchData();
  }, [lang, slug]);

  if (loading) return (
    <div style={{ minHeight: "100vh", background: "#f5f0e8", display: "flex", alignItems: "center", justifyContent: "center" }}>
      <div style={{ fontFamily: "monospace", fontSize: "13px", color: "#8a7355" }}>⏱️</div>
    </div>
  );

  if (!translation || !recipe) return (
    <div style={{ padding: "80px", textAlign: "center", fontFamily: "monospace", color: "#8a7355" }}>
      Recipe not found.
    </div>
  );

  const ingredients = Array.isArray(translation.ingredients) ? translation.ingredients : [];
  const steps = Array.isArray(translation.steps) ? translation.steps : [];
  const score = recipe.ai_score?.score;
  const cuisine = recipe.ai_score?.cuisine;
  const diet = recipe.ai_score?.diet || [];
  const course = recipe.ai_score?.course;
  const method = recipe.ai_score?.method;

  // hreflang URLs voor alle taalversies
  const hreflangTags = LANGS.map(l => ({
    lang: l,
    url: `https://culirated.com/${l}/recept/${slug}`,
  }));

  return (
    <>
      <style>{`
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { background: #f5f0e8; overflow-x: hidden; }
        .hero-img { width: 100%; height: 480px; object-fit: cover; display: block; }
        .stats-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin-bottom: 48px; }
        .ai-score-badge { position: absolute; top: 24px; right: 48px; background: rgba(255,255,255,0.95); backdrop-filter: blur(12px); border-radius: 16px; padding: 14px 18px; text-align: center; }
        .ingredients-col { position: sticky; top: 90px; }
        .detail-nav-name { display: inline; }
        .community-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; }
        @media (max-width: 768px) {
          .hero-img { height: 280px; }
          .content-grid { grid-template-columns: 1fr !important; }
          .stats-grid { grid-template-columns: repeat(2, 1fr); gap: 10px; margin-bottom: 32px; }
          .ai-score-badge { top: 16px; right: 16px; padding: 10px 14px; }
          .ingredients-col { position: static; top: auto; }
          .detail-nav-name { display: none; }
          .community-grid { grid-template-columns: repeat(2, 1fr); }
        }
        @media (max-width: 480px) {
          .community-grid { grid-template-columns: 1fr; }
        }
      `}</style>

      {/* hreflang tags */}
      <head>
        {hreflangTags.map(h => (
          <link key={h.lang} rel="alternate" hrefLang={h.lang} href={h.url} />
        ))}
        <link rel="alternate" hrefLang="x-default" href={`https://culirated.com/en/recept/${slug}`} />
        <title>{translation.title} — Culirated</title>
        <meta name="description" content={translation.description} />
        <meta property="og:title" content={translation.title} />
        <meta property="og:description" content={translation.description} />
        {recipe.image_url && <meta property="og:image" content={recipe.image_url} />}
      </head>

      <div style={{ minHeight: "100vh", background: "#f5f0e8" }}>
        {/* Top bar */}
        <div style={{ background: "#1e1609", padding: "8px 0", textAlign: "center", overflow: "hidden" }}>
          <span style={{ color: "#c8b080", fontFamily: "monospace", fontSize: "11px", letterSpacing: "1px", whiteSpace: "nowrap" }}>
            🤖 AI CREATES THE RECIPE  ·  👨‍🍳 YOU COOK IT  ·  ⭐ COMMUNITY RATES
          </span>
        </div>

        {/* Nav */}
        <nav style={{ background: "rgba(245,240,232,0.97)", backdropFilter: "blur(20px)", borderBottom: "1px solid rgba(180,160,120,0.25)", padding: "0 clamp(16px, 4vw, 48px)", position: "sticky", top: 0, zIndex: 100 }}>
          <div style={{ maxWidth: "1280px", margin: "0 auto", display: "flex", alignItems: "center", height: "60px", gap: "16px" }}>
            <a href="/" style={{ textDecoration: "none", display: "flex", alignItems: "center", gap: "10px", flexShrink: 0 }}>
              <div style={{ width: "32px", height: "32px", borderRadius: "10px", background: "linear-gradient(135deg,#2d5a27,#6aa86e)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "16px" }}>🌿</div>
              <span className="detail-nav-name" style={{ fontFamily: "Georgia, serif", fontWeight: "900", fontSize: "20px", color: "#1e1609" }}>Culirated</span>
            </a>
            <a href="/recipes" style={{ fontFamily: "monospace", fontSize: "12px", color: "#8a7355", textDecoration: "none", whiteSpace: "nowrap" }}>← {ui.allRecipes}</a>
            <div style={{ flex: 1 }} />
            <NavShareButton title={translation.title} shareLabel={ui.share} copyLabel={ui.copyLink} copiedLabel={ui.copied} />
          </div>
        </nav>

        {/* Hero image */}
        {recipe.image_url && (
          <div style={{ position: "relative" }}>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={recipe.image_url} alt={translation.title} className="hero-img" />
            <div style={{ position: "absolute", inset: 0, background: "linear-gradient(to top, rgba(30,22,9,0.7) 0%, transparent 50%)" }} />
            <div style={{ position: "absolute", bottom: "40px", left: "0", right: "0", maxWidth: "1280px", margin: "0 auto", padding: "0 clamp(16px, 4vw, 48px)" }}>
              <h1 style={{ fontFamily: "Georgia, serif", fontSize: "clamp(28px, 5vw, 52px)", fontWeight: "700", color: "#fff", lineHeight: 1.1, letterSpacing: "-1px", textShadow: "0 2px 20px rgba(0,0,0,0.3)" }}>
                {translation.title}
              </h1>
              {translation.description && (
                <p style={{ fontFamily: "Georgia, serif", fontSize: "clamp(15px, 2vw, 18px)", color: "rgba(255,255,255,0.85)", marginTop: "12px", maxWidth: "640px", lineHeight: 1.5 }}>{translation.description}</p>
              )}
              <div style={{ display: "flex", gap: "12px", marginTop: "16px", flexWrap: "wrap" }}>
                {[
                  { icon: "😍", count: recipe.reactions_want || 0 },
                  { icon: "✅", count: recipe.reactions_made || 0 },
                  { icon: "❤️", count: recipe.reactions_favorite || 0 },
                ].map(r => r.count > 0 && (
                  <div key={r.icon} style={{ display: "flex", alignItems: "center", gap: "5px", background: "rgba(255,255,255,0.15)", backdropFilter: "blur(8px)", borderRadius: "20px", padding: "5px 12px" }}>
                    <span style={{ fontSize: "16px" }}>{r.icon}</span>
                    <span style={{ fontFamily: "monospace", fontSize: "12px", color: "#fff", fontWeight: "500" }}>{r.count}</span>
                  </div>
                ))}
              </div>
            </div>
            {score && (
              <div className="ai-score-badge">
                <div style={{ fontFamily: "monospace", fontSize: "10px", color: "#8a7355", letterSpacing: "1px", marginBottom: "4px" }}>AI SCORE</div>
                <div style={{ fontFamily: "Georgia, serif", fontSize: "28px", fontWeight: "700", color: "#2d5a27", lineHeight: 1 }}>{score}</div>
                <div style={{ fontFamily: "monospace", fontSize: "10px", color: "#8a7355" }}>/100</div>
              </div>
            )}
          </div>
        )}

        {/* Content */}
        <div style={{ maxWidth: "1280px", margin: "0 auto", padding: "clamp(24px, 4vw, 48px) clamp(16px, 4vw, 48px) 80px" }}>
          {/* Meta strip */}
          <div style={{ display: "flex", gap: "8px", flexWrap: "wrap", marginBottom: "40px" }}>
            {cuisine && <span style={{ fontFamily: "monospace", fontSize: "12px", color: "#8a7355", background: "rgba(140,115,80,0.12)", borderRadius: "20px", padding: "5px 14px" }}>{cuisine}</span>}
            {course && <span style={{ fontFamily: "monospace", fontSize: "12px", color: "#4a7a3d", background: "rgba(74,122,61,0.1)", borderRadius: "20px", padding: "5px 14px" }}>{course}</span>}
            {method && <span style={{ fontFamily: "monospace", fontSize: "12px", color: "#8a7355", background: "rgba(140,115,80,0.12)", borderRadius: "20px", padding: "5px 14px" }}>{method}</span>}
            {diet.map((d: string) => <span key={d} style={{ fontFamily: "monospace", fontSize: "12px", color: "#2d5a27", background: "rgba(45,90,39,0.1)", borderRadius: "20px", padding: "5px 14px" }}>{d}</span>)}
          </div>

          {/* Stats */}
          <div className="stats-grid">
            {[
              { label: ui.prepTime, value: recipe.prep_time ? `${recipe.prep_time} ${ui.min}` : "—", icon: "⏱️" },
              { label: ui.servings, value: recipe.servings ? `${recipe.servings} ${ui.people}` : "—", icon: "👥" },
              { label: ui.calories, value: recipe.calories ? `${recipe.calories} ${ui.kcal}` : "—", icon: "🔥" },
              { label: ui.difficulty, value: recipe.difficulty || "—", icon: "📊" },
            ].map(s => (
              <div key={s.label} style={{ background: "#faf8f3", borderRadius: "14px", padding: "20px", border: "1px solid rgba(180,160,120,0.2)", textAlign: "center" }}>
                <div style={{ fontSize: "24px", marginBottom: "8px" }}>{s.icon}</div>
                <div style={{ fontFamily: "Georgia, serif", fontSize: "18px", fontWeight: "700", color: "#1e1609", marginBottom: "4px" }}>{s.value}</div>
                <div style={{ fontFamily: "monospace", fontSize: "11px", color: "#8a7355", textTransform: "uppercase", letterSpacing: "0.5px" }}>{s.label}</div>
              </div>
            ))}
          </div>

          {/* 2-col layout */}
          <div className="content-grid" style={{ display: "grid", gridTemplateColumns: "1fr 2fr", gap: "48px", alignItems: "start" }}>
            {/* Ingredients */}
            <div className="ingredients-col" style={{ background: "#faf8f3", borderRadius: "20px", padding: "32px", border: "1px solid rgba(180,160,120,0.2)" }}>
              <h2 style={{ fontFamily: "Georgia, serif", fontSize: "24px", fontWeight: "700", color: "#1e1609", marginBottom: "24px" }}>{ui.ingredients}</h2>
              {ingredients.length > 0 ? (
                <ul style={{ listStyle: "none" }}>
                  {ingredients.map((ing: string, i: number) => (
                    <li key={i} style={{ display: "flex", alignItems: "flex-start", gap: "12px", paddingBottom: "12px", borderBottom: i < ingredients.length - 1 ? "1px solid rgba(180,160,120,0.12)" : "none", marginBottom: "12px" }}>
                      <span style={{ width: "6px", height: "6px", borderRadius: "50%", background: "#3a7a32", marginTop: "7px", flexShrink: 0 }} />
                      <span style={{ fontFamily: "Georgia, serif", fontSize: "15px", color: "#1e1609", lineHeight: 1.5 }}>{ing}</span>
                    </li>
                  ))}
                </ul>
              ) : (
                <p style={{ fontFamily: "monospace", fontSize: "13px", color: "#8a7355" }}>—</p>
              )}
            </div>

            {/* Steps */}
            <div>
              <h2 style={{ fontFamily: "Georgia, serif", fontSize: "24px", fontWeight: "700", color: "#1e1609", marginBottom: "32px" }}>{ui.instructions}</h2>
              {steps.length > 0 ? (
                <div style={{ display: "flex", flexDirection: "column", gap: "24px" }}>
                  {steps.map((step: string, i: number) => (
                    <div key={i} style={{ display: "flex", gap: "20px", alignItems: "flex-start" }}>
                      <div style={{ width: "36px", height: "36px", borderRadius: "50%", background: "#1e1609", color: "#e8dfc8", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "Georgia, serif", fontSize: "15px", fontWeight: "700", flexShrink: 0, marginTop: "2px" }}>
                        {i + 1}
                      </div>
                      <div style={{ background: "#faf8f3", borderRadius: "14px", padding: "20px 24px", border: "1px solid rgba(180,160,120,0.15)", flex: 1 }}>
                        <p style={{ fontFamily: "Georgia, serif", fontSize: "16px", color: "#1e1609", lineHeight: 1.75 }}>{step}</p>
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <p style={{ fontFamily: "monospace", fontSize: "13px", color: "#8a7355" }}>—</p>
              )}

              {/* AI badge */}
              <div style={{ marginTop: "48px", background: "rgba(74,122,61,0.06)", borderRadius: "16px", padding: "24px", border: "1px solid rgba(74,122,61,0.15)", display: "flex", alignItems: "center", gap: "16px" }}>
                <div style={{ fontSize: "28px" }}>🤖</div>
                <div>
                  <div style={{ fontFamily: "monospace", fontSize: "12px", color: "#2d5a27", fontWeight: "500", marginBottom: "4px" }}>{ui.aiChecked}</div>
                  <div style={{ fontFamily: "Georgia, serif", fontSize: "14px", color: "#4a3820", lineHeight: 1.5 }}>{ui.aiText}</div>
                </div>
              </div>

              {/* Reactions */}
              <Reactions recipeId={recipe.id} initial={{ want: recipe.reactions_want || 0, made: recipe.reactions_made || 0, favorite: recipe.reactions_favorite || 0 }} whatDoYouThink={ui.whatDoYouThink} />

              {/* Share */}
              <ShareButtons title={translation.title} shareLabel={ui.share} copyLabel={ui.copyLink} copiedLabel={ui.copied} />
            </div>
          </div>

          {/* Community photos */}
          <CommunityPhotos recipeId={recipe.id} ui={ui} />
        </div>
      </div>
    </>
  );
}

// ─── Reactions ────────────────────────────────────────────────────────────────

function Reactions({ recipeId, initial, whatDoYouThink }: { recipeId: string; initial: { want: number; made: number; favorite: number }; whatDoYouThink: string }) {
  const [counts, setCounts] = useState(initial);
  const [active, setActive] = useState<string[]>([]);
  const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);

  const reactions = [
    { key: "want", icon: "😍", col: "reactions_want" },
    { key: "made", icon: "✅", col: "reactions_made" },
    { key: "favorite", icon: "❤️", col: "reactions_favorite" },
  ];

  async function toggle(key: string, col: string) {
    const isActive = active.includes(key);
    const delta = isActive ? -1 : 1;
    const newCount = Math.max(0, (counts as any)[key] + delta);
    setCounts(prev => ({ ...prev, [key]: newCount }));
    setActive(prev => isActive ? prev.filter(k => k !== key) : [...prev, key]);
    await supabase.from("recipes").update({ [col]: newCount }).eq("id", recipeId);
  }

  return (
    <div style={{ marginTop: "40px", marginBottom: "8px" }}>
      <div style={{ fontFamily: "monospace", fontSize: "11px", color: "#8a7355", letterSpacing: "1px", marginBottom: "16px", textTransform: "uppercase" }}>{whatDoYouThink}</div>
      <div style={{ display: "flex", gap: "12px", flexWrap: "wrap" }}>
        {reactions.map(r => {
          const isActive = active.includes(r.key);
          return (
            <button key={r.key} onClick={() => toggle(r.key, r.col)}
              style={{ display: "flex", alignItems: "center", gap: "8px", background: isActive ? "#1e1609" : "#faf8f3", color: isActive ? "#e8dfc8" : "#4a3820", border: `1.5px solid ${isActive ? "#1e1609" : "rgba(180,160,120,0.3)"}`, borderRadius: "24px", padding: "11px 20px", fontFamily: "monospace", fontSize: "13px", cursor: "pointer", transition: "all 0.15s" }}>
              <span style={{ fontSize: "20px" }}>{r.icon}</span>
            </button>
          );
        })}
      </div>
    </div>
  );
}

// ─── Share Buttons ────────────────────────────────────────────────────────────

function ShareButtons({ title, shareLabel, copyLabel, copiedLabel }: { title: string; shareLabel: string; copyLabel: string; copiedLabel: string }) {
  const [show, setShow] = useState(false);
  const [copied, setCopied] = useState(false);
  const ref = React.useRef<HTMLDivElement>(null);
  const url = typeof window !== "undefined" ? window.location.href : "";
  const text = encodeURIComponent(`${title} on Culirated`);
  const encodedUrl = encodeURIComponent(url);

  useEffect(() => {
    function handleClick(e: MouseEvent) {
      if (ref.current && !ref.current.contains(e.target as Node)) setShow(false);
    }
    document.addEventListener("mousedown", handleClick);
    return () => document.removeEventListener("mousedown", handleClick);
  }, []);

  const socials = [
    { label: "WhatsApp", href: `https://wa.me/?text=${text}%20${encodedUrl}`, icon: "💬" },
    { label: "Facebook", href: `https://www.facebook.com/sharer/sharer.php?u=${encodedUrl}`, icon: "📘" },
    { label: "X / Twitter", href: `https://x.com/intent/tweet?text=${text}&url=${encodedUrl}`, icon: "🐦" },
    { label: "Pinterest", href: `https://pinterest.com/pin/create/button/?url=${encodedUrl}&description=${text}`, icon: "📌" },
    { label: "Instagram", href: `https://www.instagram.com/`, icon: "📸" },
    { label: "TikTok", href: `https://www.tiktok.com/`, icon: "🎵" },
    { label: "LinkedIn", href: `https://www.linkedin.com/sharing/share-offsite/?url=${encodedUrl}`, icon: "💼" },
    { label: "Reddit", href: `https://reddit.com/submit?url=${encodedUrl}&title=${text}`, icon: "🤖" },
    { label: "Email", href: `mailto:?subject=${text}&body=${encodedUrl}`, icon: "✉️" },
  ];

  return (
    <div ref={ref} style={{ marginTop: "32px", position: "relative", display: "inline-block" }}>
      <div style={{ fontFamily: "monospace", fontSize: "11px", color: "#8a7355", letterSpacing: "1px", marginBottom: "14px", textTransform: "uppercase" }}>{shareLabel}</div>
      <button onClick={() => setShow(!show)} style={{ background: "#e8581a", border: "none", borderRadius: "20px", padding: "12px 24px", cursor: "pointer", fontFamily: "monospace", fontSize: "13px", color: "#fff", fontWeight: "500" }}>
        ↗ {shareLabel}
      </button>
      {show && (
        <div style={{ position: "absolute", bottom: "calc(100% + 8px)", left: 0, background: "#fff", borderRadius: "16px", padding: "8px", border: "1px solid rgba(180,160,120,0.2)", boxShadow: "0 12px 40px rgba(30,22,9,0.12)", zIndex: 200, minWidth: "200px", maxWidth: "calc(100vw - 32px)" }}>
          {socials.map(b => (
            <a key={b.label} href={b.href} target="_blank" rel="noopener noreferrer" style={{ textDecoration: "none" }}>
              <div style={{ display: "flex", alignItems: "center", gap: "10px", padding: "9px 14px", borderRadius: "10px", fontFamily: "monospace", fontSize: "12px", color: "#1e1609" }}
                onMouseEnter={e => (e.currentTarget.style.background = "#f5f0e8")}
                onMouseLeave={e => (e.currentTarget.style.background = "transparent")}>
                <span style={{ fontSize: "15px" }}>{b.icon}</span> {b.label}
              </div>
            </a>
          ))}
          <div onClick={() => { navigator.clipboard.writeText(url); setCopied(true); setTimeout(() => setCopied(false), 2000); }}
            style={{ display: "flex", alignItems: "center", gap: "10px", padding: "9px 14px", borderRadius: "10px", fontFamily: "monospace", fontSize: "12px", color: copied ? "#2d5a27" : "#1e1609", cursor: "pointer", borderTop: "1px solid rgba(180,160,120,0.15)", marginTop: "4px" }}
            onMouseEnter={e => (e.currentTarget.style.background = "#f5f0e8")}
            onMouseLeave={e => (e.currentTarget.style.background = "transparent")}>
            <span style={{ fontSize: "15px" }}>{copied ? "✅" : "🔗"}</span> {copied ? copiedLabel : copyLabel}
          </div>
        </div>
      )}
    </div>
  );
}

// ─── Nav Share Button ─────────────────────────────────────────────────────────

function NavShareButton({ title, shareLabel, copyLabel, copiedLabel }: { title: string; shareLabel: string; copyLabel: string; copiedLabel: string }) {
  const [show, setShow] = useState(false);
  const ref = React.useRef<HTMLDivElement>(null);
  const url = typeof window !== "undefined" ? window.location.href : "";
  const text = encodeURIComponent(`${title} on Culirated`);
  const encodedUrl = encodeURIComponent(url);

  useEffect(() => {
    function handleClick(e: MouseEvent) {
      if (ref.current && !ref.current.contains(e.target as Node)) setShow(false);
    }
    document.addEventListener("mousedown", handleClick);
    return () => document.removeEventListener("mousedown", handleClick);
  }, []);

  const socials = [
    { label: "WhatsApp", href: `https://wa.me/?text=${text}%20${encodedUrl}`, icon: "💬" },
    { label: "Facebook", href: `https://www.facebook.com/sharer/sharer.php?u=${encodedUrl}`, icon: "📘" },
    { label: "X / Twitter", href: `https://x.com/intent/tweet?text=${text}&url=${encodedUrl}`, icon: "🐦" },
    { label: "Pinterest", href: `https://pinterest.com/pin/create/button/?url=${encodedUrl}&description=${text}`, icon: "📌" },
    { label: "Instagram", href: `https://www.instagram.com/`, icon: "📸" },
    { label: "TikTok", href: `https://www.tiktok.com/`, icon: "🎵" },
    { label: "LinkedIn", href: `https://www.linkedin.com/sharing/share-offsite/?url=${encodedUrl}`, icon: "💼" },
    { label: "Reddit", href: `https://reddit.com/submit?url=${encodedUrl}&title=${text}`, icon: "🤖" },
    { label: "Email", href: `mailto:?subject=${text}&body=${encodedUrl}`, icon: "✉️" },
  ];

  return (
    <div ref={ref} style={{ position: "relative" }}>
      <button onClick={() => setShow(!show)} style={{ background: "#e8581a", border: "none", borderRadius: "20px", padding: "10px 16px", cursor: "pointer", fontFamily: "monospace", fontSize: "12px", color: "#fff", fontWeight: "500" }}>
        ↗ {shareLabel}
      </button>
      {show && (
        <div style={{ position: "absolute", top: "calc(100% + 8px)", right: 0, background: "#fff", borderRadius: "16px", padding: "8px", border: "1px solid rgba(180,160,120,0.2)", boxShadow: "0 12px 40px rgba(30,22,9,0.12)", zIndex: 200, minWidth: "200px", maxWidth: "calc(100vw - 32px)" }}>
          {socials.map(b => (
            <a key={b.label} href={b.href} target="_blank" rel="noopener noreferrer" style={{ textDecoration: "none" }}>
              <div style={{ display: "flex", alignItems: "center", gap: "10px", padding: "9px 14px", borderRadius: "10px", fontFamily: "monospace", fontSize: "12px", color: "#1e1609" }}
                onMouseEnter={e => (e.currentTarget.style.background = "#f5f0e8")}
                onMouseLeave={e => (e.currentTarget.style.background = "transparent")}>
                <span style={{ fontSize: "15px" }}>{b.icon}</span> {b.label}
              </div>
            </a>
          ))}
          <div onClick={() => { navigator.clipboard.writeText(url); setShow(false); }}
            style={{ display: "flex", alignItems: "center", gap: "10px", padding: "9px 14px", borderRadius: "10px", fontFamily: "monospace", fontSize: "12px", color: "#1e1609", cursor: "pointer", borderTop: "1px solid rgba(180,160,120,0.15)", marginTop: "4px" }}
            onMouseEnter={e => (e.currentTarget.style.background = "#f5f0e8")}
            onMouseLeave={e => (e.currentTarget.style.background = "transparent")}>
            <span style={{ fontSize: "15px" }}>🔗</span> {copyLabel}
          </div>
        </div>
      )}
    </div>
  );
}

// ─── Community Photos ─────────────────────────────────────────────────────────

function CommunityPhotos({ recipeId, ui }: { recipeId: string; ui: Record<string, string> }) {
  const [photos, setPhotos] = useState<any[]>([]);
  const [loadingPhotos, setLoadingPhotos] = useState(true);
  const [uploading, setUploading] = useState(false);
  const [preview, setPreview] = useState<string | null>(null);
  const [file, setFile] = useState<File | null>(null);
  const [name, setName] = useState("");
  const [tip, setTip] = useState("");
  const [success, setSuccess] = useState(false);
  const [error, setError] = useState("");
  const fileRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    async function fetchPhotos() {
      const { data } = await supabase
        .from("community_photos")
        .select("id, photo_url, name, tip, created_at")
        .eq("recipe_id", recipeId)
        .order("created_at", { ascending: false });
      setPhotos(data || []);
      setLoadingPhotos(false);
    }
    fetchPhotos();
  }, [recipeId]);

  function handleFileChange(e: React.ChangeEvent<HTMLInputElement>) {
    const f = e.target.files?.[0];
    if (!f) return;
    setFile(f);
    const reader = new FileReader();
    reader.onload = ev => setPreview(ev.target?.result as string);
    reader.readAsDataURL(f);
  }

  async function handleSubmit() {
    if (!file) return;
    setUploading(true);
    setError("");
    try {
      const formData = new FormData();
      formData.append("file", file);
      formData.append("recipeId", recipeId);
      formData.append("name", name);
      formData.append("tip", tip);
      const res = await fetch("/api/community-photo", { method: "POST", body: formData });
      const data = await res.json();
      if (data.error) { setError(ui.errorMsg); setUploading(false); return; }
      setSuccess(true);
      setFile(null); setPreview(null); setName(""); setTip("");
      const { data: fresh } = await supabase.from("community_photos").select("id, photo_url, name, tip, created_at").eq("recipe_id", recipeId).order("created_at", { ascending: false });
      setPhotos(fresh || []);
    } catch { setError(ui.errorMsg); }
    setUploading(false);
  }

  return (
    <div style={{ marginTop: "80px" }}>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "32px", marginBottom: "48px" }}>
        {/* Upload */}
        <div style={{ background: "#faf8f3", borderRadius: "20px", padding: "32px", border: "1px solid rgba(180,160,120,0.2)", display: "flex", flexDirection: "column", gap: "16px" }}>
          <h3 style={{ fontFamily: "Georgia, serif", fontSize: "22px", fontWeight: "700", color: "#1e1609" }}>{ui.madeThis}</h3>
          <p style={{ fontFamily: "monospace", fontSize: "12px", color: "#8a7355" }}>{ui.madeThisSub}</p>
          {success ? (
            <div style={{ background: "rgba(74,122,61,0.08)", borderRadius: "12px", padding: "20px", textAlign: "center", fontFamily: "monospace", fontSize: "13px", color: "#2d5a27" }}>✅ {ui.successMsg || "Posted!"}</div>
          ) : (
            <>
              <input type="file" id="community-upload" accept="image/*" onChange={handleFileChange} style={{ display: "none" }} ref={fileRef} />
              {!preview ? (
                <label htmlFor="community-upload" style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: "10px", border: "2px dashed rgba(232,88,26,0.3)", borderRadius: "16px", padding: "32px", cursor: "pointer", fontFamily: "monospace", fontSize: "13px", color: "#e8581a", background: "rgba(232,88,26,0.03)" }}>
                  <span style={{ fontSize: "24px" }}>📷</span>{ui.uploadPhoto}
                </label>
              ) : (
                <div style={{ position: "relative", borderRadius: "16px", overflow: "hidden" }}>
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img src={preview} alt="preview" style={{ width: "100%", aspectRatio: "4/3", objectFit: "cover", display: "block" }} />
                  <label htmlFor="community-upload" style={{ position: "absolute", bottom: "12px", right: "12px", background: "rgba(30,22,9,0.7)", backdropFilter: "blur(8px)", borderRadius: "20px", padding: "7px 14px", fontFamily: "monospace", fontSize: "12px", color: "#fff", cursor: "pointer" }}>
                    {ui.changePhoto}
                  </label>
                </div>
              )}
              <input type="text" placeholder={ui.yourName} value={name} maxLength={80} onChange={e => setName(e.target.value)}
                style={{ background: "#faf8f3", border: "1px solid rgba(180,160,120,0.3)", borderRadius: "12px", padding: "12px 16px", fontFamily: "Georgia, serif", fontSize: "15px", color: "#1e1609", outline: "none" }} />
              <textarea placeholder={ui.yourTip} value={tip} maxLength={300} rows={3} onChange={e => setTip(e.target.value)}
                style={{ background: "#faf8f3", border: "1px solid rgba(180,160,120,0.3)", borderRadius: "12px", padding: "12px 16px", fontFamily: "Georgia, serif", fontSize: "15px", color: "#1e1609", outline: "none", resize: "vertical" }} />
              {error && <p style={{ fontFamily: "monospace", fontSize: "12px", color: "#c43d00" }}>{error}</p>}
              <button onClick={handleSubmit} disabled={!file || uploading}
                style={{ background: file && !uploading ? "#e8581a" : "rgba(180,160,120,0.3)", color: "#fff", border: "none", borderRadius: "24px", padding: "14px 28px", fontFamily: "monospace", fontSize: "13px", fontWeight: "600", cursor: file && !uploading ? "pointer" : "not-allowed" }}>
                {uploading ? "…" : ui.post}
              </button>
            </>
          )}
        </div>
        {/* Teaser */}
        <div style={{ background: "linear-gradient(135deg,#1e1609,#2d5a27)", borderRadius: "20px", padding: "40px 32px", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", textAlign: "center" }}>
          <div style={{ fontSize: "48px", marginBottom: "20px" }}>👨‍🍳</div>
          <div style={{ fontFamily: "Georgia, serif", fontSize: "22px", fontWeight: "700", color: "#e8dfc8", lineHeight: 1.3, marginBottom: "12px" }}>{ui.cookIt}</div>
          <div style={{ fontFamily: "monospace", fontSize: "12px", color: "#8a7355", lineHeight: 1.7 }}>{ui.cookItSub}</div>
          <div style={{ marginTop: "20px", fontFamily: "monospace", fontSize: "11px", color: "#6b5840" }}>#culirated</div>
        </div>
      </div>

      {!loadingPhotos && photos.length > 0 && (
        <div>
          <h3 style={{ fontFamily: "Georgia, serif", fontSize: "24px", fontWeight: "700", color: "#1e1609", marginBottom: "24px" }}>{ui.communityTitle}</h3>
          <div className="community-grid">
            {photos.map((p) => (
              <div key={p.id} style={{ borderRadius: "16px", overflow: "hidden", background: "#faf8f3", border: "1px solid rgba(180,160,120,0.2)" }}>
                <div style={{ aspectRatio: "4/3", overflow: "hidden" }}>
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img src={p.photo_url} alt={p.name || ""} style={{ width: "100%", height: "100%", objectFit: "cover", display: "block" }} />
                </div>
                {(p.name || p.tip) && (
                  <div style={{ padding: "14px 16px" }}>
                    {p.name && <div style={{ fontFamily: "monospace", fontSize: "11px", color: "#8a7355", marginBottom: "4px" }}>👨‍🍳 {p.name}</div>}
                    {p.tip && <div style={{ fontFamily: "Georgia, serif", fontSize: "14px", color: "#4a3820", lineHeight: 1.5 }}>{p.tip}</div>}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
