import StaticPageClient from "../StaticPageClient";

function TermsContent() {
  return (
    <>
      <div className="label">TERMS OF USE</div>
      <h1>Terms of Use</h1>
      <div className="date">Last updated: March 2026</div>
      <h2>About Culirated</h2>
      <p>Culirated (culirated.com) is an AI-powered recipe platform. All recipes are automatically generated by AI and do not come from human authors unless otherwise stated.</p>
      <hr className="divider" />
      <h2>Use of recipes</h2>
      <ul>
        <li>Recipes on Culirated are free to use for personal, non-commercial use.</li>
        <li>Commercial use or mass reproduction of recipes is not permitted without permission.</li>
        <li>Dietary labels (gluten-free, vegan, etc.) are AI-assessed. Always check packaging if you have allergies.</li>
      </ul>
      <hr className="divider" />
      <h2>Community photo uploads</h2>
      <ul>
        <li>By uploading a photo you give Culirated permission to display that photo on the relevant recipe page.</li>
        <li>Only upload photos you have taken yourself. Do not upload photos of others without permission.</li>
        <li>Do not upload offensive, illegal or non-food related photos. Uploads are checked by AI.</li>
        <li>Culirated reserves the right to remove photos that do not comply with these terms.</li>
      </ul>
      <hr className="divider" />
      <h2>Liability</h2>
      <p>Culirated is not liable for damage resulting from the use of recipes on this platform. Recipes are AI-generated and may contain errors. Always follow food safety guidelines when preparing and storing food.</p>
      <hr className="divider" />
      <h2>Changes</h2>
      <p>Culirated reserves the right to change these terms at any time. The most recent version is always available at culirated.com/terms.</p>
      <hr className="divider" />
      <h2>Contact</h2>
      <p>Questions? Email us at <a href="mailto:culirated@gmail.com">culirated@gmail.com</a>.</p>
    </>
  );
}

export default function TermsPage() {
  return (
    <>
      <style>{`
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { background: #f5f0e8; font-family: Georgia, serif; color: #1e1609; }
        .content { max-width: 720px; margin: 0 auto; padding: clamp(48px, 8vw, 96px) clamp(16px, 4vw, 48px); }
        h1 { font-size: clamp(32px, 5vw, 52px); font-weight: 900; letter-spacing: -1px; line-height: 1.1; margin-bottom: 12px; }
        h2 { font-size: 22px; font-weight: 700; margin-bottom: 12px; margin-top: 40px; color: #1e1609; }
        p { font-size: 16px; line-height: 1.8; color: #4a3820; margin-bottom: 16px; }
        ul { margin: 0 0 16px 24px; }
        li { font-size: 16px; line-height: 1.8; color: #4a3820; margin-bottom: 6px; }
        .label { font-family: monospace; font-size: 12px; color: #e8581a; letter-spacing: 2px; margin-bottom: 16px; }
        .date { font-family: monospace; font-size: 12px; color: #8a7355; margin-bottom: 48px; }
        .divider { border: none; border-top: 1px solid rgba(180,160,120,0.2); margin: 40px 0; }
        a { color: #2d5a27; }
        .translated-content h1 { font-size: clamp(32px, 5vw, 52px); font-weight: 900; letter-spacing: -1px; line-height: 1.1; margin-bottom: 12px; }
        .translated-content h2 { font-size: 22px; font-weight: 700; margin-bottom: 12px; margin-top: 40px; }
        .translated-content p { font-size: 16px; line-height: 1.8; color: #4a3820; margin-bottom: 16px; }
        .translated-content ul { margin: 0 0 16px 24px; }
        .translated-content li { font-size: 16px; line-height: 1.8; color: #4a3820; margin-bottom: 6px; }
        .translated-content hr { border: none; border-top: 1px solid rgba(180,160,120,0.2); margin: 40px 0; }
        .translated-content a { color: #2d5a27; }
      `}</style>
      <div style={{ background: "#1e1609", padding: "8px 16px", textAlign: "center" }}>
        <span style={{ color: "#c8b080", fontFamily: "monospace", fontSize: "11px", letterSpacing: "1px" }}>
          AI CREATES THE RECIPE  ·  YOU COOK IT  ·  COMMUNITY RATES
        </span>
      </div>
      <nav style={{ background: "rgba(245,240,232,0.97)", backdropFilter: "blur(20px)", borderBottom: "1px solid rgba(180,160,120,0.25)", padding: "0 clamp(16px, 4vw, 48px)" }}>
        <div style={{ maxWidth: "1280px", margin: "0 auto", display: "flex", alignItems: "center", height: "60px", gap: "16px" }}>
          <a href="/" style={{ textDecoration: "none", display: "flex", alignItems: "center", gap: "10px" }}>
            <div style={{ width: "32px", height: "32px", borderRadius: "10px", background: "linear-gradient(135deg,#2d5a27,#6aa86e)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "16px" }}>&#x1F33F;</div>
            <span style={{ fontFamily: "Georgia, serif", fontWeight: "900", fontSize: "20px", color: "#1e1609" }}>Culirated</span>
          </a>
          <a href="/" style={{ fontFamily: "monospace", fontSize: "12px", color: "#8a7355", textDecoration: "none" }}>Back to Culirated</a>
        </div>
      </nav>
      <div className="content">
        <StaticPageClient page="terms">
          <TermsContent />
        </StaticPageClient>
      </div>
      <footer style={{ borderTop: "1px solid rgba(180,160,120,0.2)", padding: "clamp(24px, 4vw, 40px) clamp(16px, 4vw, 48px)", textAlign: "center" }}>
        <a href="/" style={{ fontFamily: "monospace", fontSize: "12px", color: "#8a7355", textDecoration: "none" }}>Back to Culirated</a>
      </footer>
    </>
  );
}
